name: shell commands
on: push
jobs:
    run-shell command
    runs-on: ubuntu-latest
    steps:
        - name: checkout
        uses: actions/checkout@3
        - name: echo string
         run: echo "Hello"
        - name: multiline script
          run: |
           node -v
           pwd 
         